### ISSUE TITLE
Support for traits

### ISSUE THREAD

**Issue by aik099** [php-annotations/php-annotations#103]
Currently annotations from properties/methods declared in traits used by scanned class are not accessible at all:

```php
<?php

trait TestTrait
{
    /**
     * @var SomeType
     */
    public $member;
}

class Test {
     use TestTrait;   
}
```

See #102, were failing test case is added.

Here is how I see it implemented:

1. in `AnnotationParser` add support for `trait` token so that traits can be scanned for annotations as regular classes (maybe we already support that)
2. in the `AnnotationManager::getAnnotations` method, when returning class methods/properties use `ReflectionClass::getTraits` method to add methods/properties from traits to the list (usual trait inheritance rules apply)

The https://github.com/FriendsOfPHP/Sami/pull/93/files shows the trait conflict resulution logic.

**Comment by aik099** [comment]
Not sure how to deal with method substitutions in traits though, e.g.

@benesch

```php
class Aliased_Talker {
    use A, B {
        B::smallTalk insteadof A;
        A::bigTalk insteadof B;
        B::bigTalk as talk;
    }
}
```

Here both methods are defined in both traits and in final class we need to parse "insteadof" to understand that.

**Comment by mindplay-dk** [comment]
> Not sure how to deal with method substitutions in traits

Right, good point. (I avoid using traits, so this didn't occur to me.)

Hmm, maybe it's time to think about swapping out my little "just enough" parser with a full, static reflection library? The one from [phpDocumentor](https://github.com/phpDocumentor/Reflection) supports traits. (I haven't found any others that do.)

I would think twice before swapping out the tag-parser etc. though - our parser treats tag content in a very specific way, likely not compatible with the way phpDocumentor treats them. Using the static reflection library is probably a good idea though - if maintaining my custom parser is becoming too much of a chore...

**Comment by benesch** [comment]
The phpDoc one looks like it no longer supports PHP 5.3. I don't think it'll be too hard to extend your custom parser—I'll give it a go!

**Comment by mindplay-dk** [comment]
@benesch bear in mind backwards compatibility - new token constants, such as the one for `insteadof`, are going to be undefined in older versions of PHP.

**Comment by aik099** [comment]
@mindplay-dk is trait support:

* a bugfix - because annotations from traits were not recognized and it's fixed now
* a feature - before library had no support for traits and now they are supported

?

I'm asking because I want to know if next release should 1.2.1 or 1.3.0?

**Comment by mindplay-dk** [comment]
I'd say it's a feature - non-support for a given feature is not a bug :-)
