### ISSUE TITLE
Introduce cache format versioning

### ISSUE THREAD

**Issue by aik099** [php-annotations/php-annotations#107]
We've changed cache file format (added new properties) few times in the past. When new library code is used to parse old cache format, then this results in PHP notices about accessing missing cache keys.

I propose to:

1. add `AnnotationManager::CACHE_FORMAT_VERSION` constant with value of 3
2. write constant value to each cached parsed file
3. when reading cache file and it's either missing cache format version or version is smaller then one in the constant consider cache as invalid and parse anyway

**Comment by mindplay-dk** [comment]
Perhaps just append a version number when [assigning the cache seed](https://github.com/php-annotations/php-annotations/blob/master/src/annotations/AnnotationManager.php#L149)?

**Comment by aik099** [comment]
In that case you'll have old cache files in `/tmp` until server reboots.

**Comment by aik099** [comment]
Actually cache version can be part of the seed, but the seed needs to be stored as part of cached file rather then be part of cached filename as done in https://github.com/php-annotations/php-annotations/blob/master/src/annotations/AnnotationManager.php#L196 

This way all that differentiates caches for same PHP file would be in seed and that cache file would auto-updated when new annotations library version would be released, that have new features (e.g. trait support).

**Comment by aik099** [comment]
@mindplay-dk , what for `$cacheSeed` is needed? The only usage I can think of is:

1. configure 2 annotation managers with same cache folder, but different supported annotations
2. use each annotation manager on same PHP file
3. have 2 caches exist in parallel (because we cache resolved annotation class names)

Probably a valid use case, but does anybody use it like this?

If change cache seed to be part of cached file (as I've proposed), then above use case won't be valid anymore because one annotation manager would overwrite other annotation manager cache :smile:

**Comment by mindplay-dk** [comment]
> If change cache seed to be part of cached file (as I've proposed), then above use case won't be valid anymore

That would change the *meaning* of what `$_cacheSeed` is - probably not a good idea.

I don't understand what possible good the cache seed would be if stored. If you have to store anything, store the `CACHE_FORMAT_VERSION`, I guess?

Not that I completely understand why you'd need to store that either - just change the checksum calculation from `crc32($path . $this->_cacheSeed)` to `crc32($path . $this->_cacheSeed . self::CACHE_FORMAT_VERSION)` and effectively the cache will invalidate if the version number is changed?

**Comment by aik099** [comment]
> I don't understand what possible good the cache seed would be if stored. If you have to store anything, store the CACHE_FORMAT_VERSION, I guess?

That is something I thought about as well to preserve behavior of cache seed and allow cache versioning at same time.

> Not that I completely understand why you'd need to store that either - just change the checksum calculation from `crc32($path . $this->_cacheSeed)` to `crc32($path . $this->_cacheSeed . self::CACHE_FORMAT_VERSION)` and effectively the cache will invalidate if the version number is changed?

That would be fine if the cache is stored not on file system. As I've explained before this would double the amount of cache files that are created. Basically for each cache format change we need to store another cache file for same parsed PHP file. Cache files in old cache format won't ever be deleted.

**Comment by mindplay-dk** [comment]
> Cache files in old cache format won't ever be deleted.

Not an issue on dev systems - and on production systems, either you'd have
deployment scripts that clear various cache folders, or you can clear them
yourself.

We're talking about a few KB of files, most likely - I don't think there's
any reason to blow this tiny problem out of proportion? ;-)

**Comment by aik099** [comment]
OK. WIll do as you suggested in https://github.com/php-annotations/php-annotations/issues/107#issuecomment-183693845.

**Comment by aik099** [comment]
PR created and ready for review.
