### ISSUE TITLE
get all annotations defined in a class on methods or properties 

### ISSUE THREAD

**Issue by jcheron** [php-annotations/php-annotations#119]
Hello,
I created an annotation : 
```php
namespace test\annotations;
use mindplay\annotations\Annotation;
class IdAnnotation extends Annotation {}
```
I configured the manager : 
```php
Annotations::$config['cache'] = new AnnotationCache(__DIR__ . '/runtime');
$annotationManager->registry['id'] = 'test\annotations\IdAnnotation';
```

I created a class using the annotation : 
```php
class User{
	/**
	* @id
	*/
	private $code;
}
```

And know, I want to get the field with the @id annotation, in the User class : 

At first, I try to return all the annotations defined on the User class : 

`mindplay\annotations\Annotations::ofClass("User")` returns an empty array `array(0) { } `

`mindplay\annotations\Annotations::getManager()->getClassAnnotations("User")` returns an empty array `array(0) { } `

What is the problem ?

**Comment by aik099** [comment]
It doesn't work like that.

Here is how it works:

* the `getClassAnnotations` method returns annotations declared on a class
* the `getPropertyAnnotations` method returns annotations declared on a property
* the `getMethodAnnotations` method returns annotations declared on a method

Code example:

```php
/**
 * @class-annotation
 */
class Person
{
    /**
     * @property-annotation
     */
    public $name;

    /**
     * @method-annotation
     */
    public function testMethod()
    {
        
    }
}
```

What you're trying it get, if I understood correctly, is properties/methods of a given class/interface/trait that have given annotation. Sort of reverse lookup.

This isn't supported currently, but would be a great feature.

**Comment by jcheron** [comment]
Yes, that's it
Thank you for your answer
I will therefore stay with the old Addendum, more maintained, and not respecting PSR-4 autoloading

**Comment by aik099** [comment]
Considering that methods return annotation class instances I'm not sure how to detect which annotation belongs to which property/method.

**Comment by aik099** [comment]
@jcheron , but you'll get all properties/methods with given annotation in Addendum (repo: https://github.com/jsuchal/addendum). I've haven't found any example of that in docs.

**Comment by mindplay-dk** [comment]
@jcheron if I understand correctly, what you're really trying to do, is enumerate all properties and get their `@id` annotations?

What you're trying to do is just reflection - this operation is covered by the Reflection API in PHP:

```php
$reflection = new ReflectionClass(User::class);

foreach ($reflection->getProperties() as $property) {
    $annotations = Annotations::ofProperty(User::class, $property->name, "id");

    foreach ($annotations as $annotation) {
        // ...
    }
}
```

There's no reason why the annotation library should need to duplicate or replace the reflection API.

**Comment by jcheron** [comment]
You're right @aik099, with Addendum I was also using the reflection API, as suggested by @mindplay-dk .
I'll do the same thing with php-annotations.

The problem is especially that when I call:
`Annotations::getManager()->getPropertyAnnotations("Host","id","@id")`
I always have the same message:
`Error!: The class 'micro\annotations\IdAnnotation' must have exactly one UsageAnnotation`

**Comment by aik099** [comment]
For each annotation class you need to specify `@usage` annotation that would tell:

* where this annotation is allowed to be used: class, property, method or all of them
* will this annotation value be inherited from parent class or not

There is an example in docs: http://php-annotations.readthedocs.io/en/latest/CustomAnnotations.html

**Comment by jcheron** [comment]
ok !
`@usage` is the equivalent of Addendum `@Target`

I was wrong of reading the documentation diagonally.

I use the annotations in a small ORM.
I realize benchmarks: see [ORM benchmark](http://slam.kobject.net/php-orm-benchmark/)
It seems that the Addendum migration to php-annotations doubled performance.
Thank you very much for that, and for the answers

**Comment by aik099** [comment]
Yes, much if not all decisions made during this library development was driven by performance.

Thank you for choosing this library.
