### ISSUE TITLE
not find Annotation define .

### ISSUE THREAD

**Issue by wuchuguang** [php-annotations/php-annotations#124]
```
use Annotation\Config\ConfigType;
/**
* @ConfigType()
**/
public function xxx(){
}
```

'Annotation type \'ConfigType\' does not exist'
[2017-10-19 17:59:31] mindplay\annotations\AnnotationException: Annotation type 'ConfigType' does not exist in /opt/rondaful-b2c/msf-server/vendor/mindplay/annotations/src/annotations/AnnotationParser.php:423

**Comment by aik099** [comment]
I see you're attempting to use annotations through `use ...` statement as done in Doctrine Annotations. In this library it works differently:

1. you can use annotation without importing
2. when the AnnotationManager you need to specify mapping between annotation used in DocBlocks and class, that handles it

Example code, when :

```php
$annotationManager->registry['ConfigType'] = 'Annotation\Config\ConfigType';
```

If you haven't created annotation manager object by hand, then use `Annotations::getManager()` to obtain current annotation manager.

**Comment by wuchuguang** [comment]
i see, can support Doctrine Annotations. statement. That is perfect with phpstorm

**Comment by aik099** [comment]
If you'd like you can send a PR to support annotation self-registration based on `use ...` statements.
