### ISSUE TITLE
Error when usign @var for local variables

### ISSUE THREAD

**Issue by seblaz** [php-annotations/php-annotations#131]
Hi,
when using the @var annotation for a local variable (https://stackoverflow.com/questions/14462390/how-to-declare-the-type-for-local-variables-using-phpdoc-notation) it fails with the error `Annotation type 'mindplay\annotations\standard\VarAnnotation' cannot be applied to a method`. When the annotation is removed, it works fine. I don't expect php-annotations to support local variables but I think that it shouldn't raise the error, is that posibble or are there any limitations?

**Comment by aik099** [comment]
Which of these forms have you used:

1. /** @var $job MyJobObject */
2. /** @var MyJobObject $job */

Can you please also provide a code example (both file you test and how you test it) that fails?

**Comment by mindplay-dk** [comment]
Annotations have constraints to help you apply them correctly.

You are of course free to override `AnnotationManager::$registry["var"]` with your own class with constraints that work for your use-case.

But why would apply `@var` to a method?

**Comment by mindplay-dk** [comment]
Wait, sorry, I misread - you're applying annotations to a local variable.

@aik099 I don't think it's supposed to pick those up in the first place? much less throw errors - it's not like there'd be any way to retrieve annotations applied to variables, so there's no reason it should pick those up or construct them, is there?

**Comment by mindplay-dk** [comment]
It doesn't look like we have test coverage for that case - this might be a bug?

**Comment by aik099** [comment]
@mindplay-dk , 

1. yes, we're missing test coverage for this case;
2. last time I've checked tokenizer it's not searching for local variables at all.

**Comment by mindplay-dk** [comment]
> 2. last time I've checked tokenizer it's not searching for local variables at all. 

Yeah, glossing over the parser, I'm not convinced it would pick up doc-blocks if they aren't on the same level of nesting as the member they're being applied to.

@seblaz if you want someone to follow up on this issue, I suggest you post a repro, or (ideally) a failing test-case.

**Comment by seblaz** [comment]
Hi, I tried to reproduce the issue in a small example but I couldn't, so I will close the issue for now. I'll open it again if I can reproduce it. Thanks!
