### ISSUE TITLE
Update CodeCov integration

### ISSUE THREAD

**Issue by aik099** [php-annotations/php-annotations#143]
@mindplay-dk , please make me an admin of the https://github.com/php-annotations organization to simplify the maintenance of this project.

I've tried to change the configuration of the CodeCov integration but was faced with a `No Permission` dialog, that recommended contacting you with this message:

### CodeCov Message
Hello, could you help approve the installation of the Codecov app on GitHub for our organization? 
Here's the link: https://github.com/apps/codecov/installations/select_target

**Comment by mindplay-dk** [comment]
You are an admin already.

I would have to make you the owner, apparently.

I approved the request though, let me know if that was enough?

(Otherwise, I guess I'll make you the owner - I don't plan on doing anything with this project myself.)

**Comment by mindplay-dk** [comment]
@aik099 alright, you're now an owner. I trust you. please don't throw me out. 😅
