### ISSUE TITLE
Store documentation not in the Wiki

### ISSUE THREAD

**Issue by aik099** [php-annotations/php-annotations#37]
The GitHub Pages (http://pages.github.com/) is far more superior project website generation tool then the GitHub Wiki (https://github.com/gollum/gollum powered).

I recommend to use it.

**Comment by aik099** [comment]
It turns out there is better place for hosting documentation: https://readthedocs.org/ . I think I'll go that way.

**Comment by aik099** [comment]
Do you prefer having documentation:
* in same repo in `docs/` sub-folder
* or in dedicates `php-annotations/docs` repo?

**Comment by aik099** [comment]
Here is what I have so far: http://php-annotations.readthedocs.org/

Several issues I've found:

1. some documentation areas are missing (just `...` in there)
2. DemoScript like in https://github.com/php-annotations/php-annotations/wiki/DemoScript is totally unusable and I think I won't use table at all and just replace `#` with empty text to create nice look on RTD
3. some documentation parts reference non-existing stuff:
 * LengthAnnotation is mentioned as standard, but we've moved it to separate branch for now
 * description of some annotation (e.g. VarAnnotation) doesn't match the reality
4. too long page names

**Comment by mindplay-dk** [comment]
All this hassle, for what? A blue theme? What was so wrong with the GitHub Wiki? :-)

**Comment by aik099** [comment]
Not only that. For example with Wiki:

* you can't contribute
* no syntax highlighting
* wrapping occurs
* small page width
* non searcheable

Maybe there is something else.

**Comment by mindplay-dk** [comment]
Heh, well, it's a Wiki - so of course you can allow contributions... uncheck the "Restrict editing" settings on the settings screen.

Don't know about the other issues, but it seems like this thing (or any other thing) is just going to have it's own unique set of issues ;-)
